app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, login_required, logout_user
from app import db
from app.forms import RegistrationForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    from app.models import User
    form = RegistrationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            hashed_password = generate_password_hash(password, method='sha256')
            new_user = User(username=username, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            
            return redirect(url_for('auth.login'))
    return render_template('register.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    from app.models import User
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            user = User.query.filter_by(username=username).first()
            
            if user and check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('main.home'))
        
    return render_template('login.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app import db
from app.forms import LeagueForm, TournamentForm, MatchForm
from werkzeug.security import generate_password_hash

main = Blueprint('main', __name__)

@main.route("/")
#index
@main.route("/index", methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form.get('login'):
            return redirect(url_for('auth.login'))
        
        if request.form.get('register'):
            return redirect(url_for('auth.register'))
        
    return render_template('index.html')
    
#home page 
@main.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    return render_template('home.html')

#create league
@main.route('/create_l', methods=['GET', 'POST'])
@login_required
def create_l():
    from app.models import League, Player, Deck
    form = LeagueForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            league_name = form.league_name.data
            existing_league = League.query.filter_by(user=current_user, league_name=league_name, active=True).first()
            if existing_league:
                return render_template('create_l.html', form=form)
            
            new_league = League(league_name=league_name, user=current_user)
            db.session.add(new_league)
            db.session.commit()

            player_names = [form.player1.data, form.player2.data, form.player3.data, form.player4.data]
            for name in player_names:
                if name:
                    player = Player(player_name=name, league=new_league)
                    db.session.add(player)

            deck_names = [form.deck1.data, form.deck2.data, form.deck3.data, form.deck4.data, form.deck5.data, form.deck6.data]
            for name in deck_names:
                if name:
                    deck = Deck(deck_name=name, related_league=new_league)
                    db.session.add(deck)

            db.session.commit()

            return redirect(url_for('main.current_l'))
    
    return render_template('create_l.html', form=form)

#current league
@main.route('/current_l', methods=['GET', 'POST'])
@login_required
def current_l():
    from app.models import League

    active_leagues = League.query.filter_by(user=current_user, active=True).all()

    return render_template('current_l.html', active_leagues=active_leagues)


#create tournament
@main.route('/create_t', methods=['GET', 'POST'])
@login_required
def create_t():
    from app.models import League, Tournament, Player, Deck, PlayerScore
    form = TournamentForm()

    league_id = request.args.get('league_id')
    
    league = League.query.filter_by(id=league_id).first()
    players = []
    decks = []

    if league:
        players = Player.query.filter_by(league_id=league.id).all()
        decks = Deck.query.filter_by(league_id=league.id).all()

    if request.method == 'POST':    
        if form.validate_on_submit():
            form.players.data = request.form.getlist('players')
            form.decks.data = request.form.getlist('decks')

            tournament_name = form.tournament_name.data

            existing_tournament = Tournament.query.filter_by(tournamentsuser=current_user, tournament_name=tournament_name, active=True).first()
            if existing_tournament:
                return render_template('create_t.html', league_id=league_id, league=league, form=form, players=players, decks=decks)
            
            selected_players = form.players.data
            selected_decks = form.decks.data
            
            tournament = Tournament(tournament_name=tournament_name, league=league, tournamentsuser=current_user)
            db.session.add(tournament)
            db.session.commit()

            for player_id in selected_players:
                player = Player.query.get(int(player_id))
                tournament.participants.append(player)
                player_score = PlayerScore(player=player, tournament=tournament)
                db.session.add(player_score)

            for deck_id in selected_decks:
                deck = Deck.query.get(int(deck_id))
                tournament.decks.append(deck)

            db.session.commit()

            return redirect(url_for('main.current_t', league_id=league_id))
            
    return render_template('create_t.html', form=form, league=league, players=players, decks=decks)

#current tournament
@main.route('/current_t', methods=['GET', 'POST'])
@login_required
def current_t():
    from app.models import Tournament, League, PlayerScore
    
    league_id = request.args.get('league_id')
    
    league = League.query.filter_by(id=league_id).first()
    
    tournaments = Tournament.query.filter_by(league=league).all()

    player_scores = PlayerScore.query.all()

    
    if request.method == 'POST':
        tournament_id = request.form.get('tournament_id')

        if tournament_id:
            return redirect(url_for('main.create_m', tournament_id=tournament_id))

    return render_template('current_t.html', league=league, tournaments=tournaments, player_scores=player_scores)

#create match
@main.route('/create_m', methods=['GET', 'POST'])
@login_required
def create_m():
    from app.models import Tournament, Match, Deck, PlayerScore
    form = MatchForm()

    tournament_id = request.args.get('tournament_id')
    
    tournament = Tournament.query.filter_by(id=tournament_id).first()

    tournament_players = tournament.participants

    tournament_decks = tournament.decks
    
    def check_duplicates(list):
        seen = set()
        for num in list:
            if num in seen:
                return True
            seen.add(num)
        return False
            
    if request.method == 'POST':
        form.selectdecks.data = request.form.getlist('selectdecks')
        selected_decks = form.selectdecks.data
        
        if check_duplicates(selected_decks):
            return redirect(url_for('main.create_m', tournament_id=tournament_id, form=form, tournament=tournament, tournament_players=tournament_players, tournament_decks=tournament_decks))

        form.winner.data = request.form.getlist('winner')
        winners = form.winner.data

        match = Match(tournament=tournament)

        for player in tournament_players:

            if str(player.id) in winners:

                player_score = PlayerScore.query.filter_by(player_id=player.id, tournament_id=tournament.id).first()
                
                if player_score:
                    player_score.score += 1

                match.winners.append(player)

        for deck_id in selected_decks:    
            decks = Deck.query.get(int(deck_id))
            match.matchdecks.append(decks)
    

        db.session.add(match)
        db.session.commit()

        return redirect(url_for('main.current_m', tournament_id=tournament_id))
             
    return render_template('create_m.html', form=form, tournament=tournament, tournament_players=tournament_players, tournament_decks=tournament_decks)

#current tournament matches
@main.route('/current_m', methods=['GET', 'POST'])
@login_required
def current_m():
    from app.models import Tournament, Match
    
    tournament_id = request.args.get('tournament_id')

    tournament = Tournament.query.filter_by(id=tournament_id, active=True).first()
    
    matches = Match.query.filter_by(tournament=tournament).all()

    
    return render_template('current_m.html', tournament=tournament, matches=matches)


#app settings
@main.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    from app.models import Match

    match_id = request.args.get('match_id')
    tournament_id = request.args.get('tournament_id')
    
    match = Match.query.filter_by(id=match_id).first()

    if request.method == 'POST':
        db.session.delete(match)
        db.session.commit()
        return redirect(url_for('main.current_m', tournament_id=tournament_id))
            
    return render_template('delete.html', match=match)


@main.route('/eliminate', methods=['GET', 'POST'])
@login_required
def eliminate():
    from app.models import League, Tournament, Match
    from app.forms import EliminateForm

    form = EliminateForm()

    leagues = League.query.filter_by(user=current_user, active=True).all()

    tournaments = Tournament.query.filter_by(tournamentsuser=current_user, active=True).all()

    if request.method == 'POST':
        form.leagues.data = request.form.getlist('leagues')
        leagueslist = form.leagues.data

        form.tournaments.data = request.form.getlist('tournaments')
        tournamentslist = form.tournaments.data

        for league in leagues:
            if str(league.id) in leagueslist:
                db.session.delete(league)

        for tournament in tournaments:
            if str(tournament.id) in tournamentslist:
                db.session.delete(tournament)

        db.session.commit()

        return redirect(url_for('main.home'))
                
    return render_template('eliminate.html', form=form, leagues=leagues, tournaments=tournaments)

@main.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    from app.models import User
    from app.forms import ChangeForm

    form = ChangeForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            new_username = form.username.data
            new_password = form.password.data
            hashed_password = generate_password_hash(new_password, method='sha256')


app/templates/create_l.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Create League</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="create_l-header">
        <h1 class="create_l-h1">CREATE LEAGUE</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div class="create_l">
        <form method="POST" action="{{ url_for('main.create_l') }}">
            {{ form.hidden_tag() }}
            <div class="create_l-form">
                <label for="league_name" id="league_name" class="label">League Name</label>
                <input type="text" name="league_name" class="create_l-input" required>
            </div>
            <div class="create_l-form">
                <label for="player1" id="player1" class="label">1.Player Name</label>
                <input type="text" name="player1" class="create_l-input" required>
            </div>
            <div class="create_l-form">
                <label for="player2" id="player2" class="label">2.Player Name</label>
                <input type="text" name="player2" class="create_l-input" required>
            </div>
            <div class="create_l-form">
                <label for="player3" id="player3" class="label">3.Player Name</label>
                <input type="text" name="player3" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="player4" id="player4" class="label">4.Player Name</label>
                <input type="text" name="player4" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck1" id="deck1" class="label">1.Deck</label>
                <input type="text" name="deck1" class="create_l-input" required>
            </div>
            <div class="create_l-form">
                <label for="deck2" id="deck2" class="label">2.Deck</label>
                <input type="text" name="deck2" class="create_l-input" required>
            </div>
            <div class="create_l-form">
                <label for="deck3" id="deck3" class="label">3.Deck</label>
                <input type="text" name="deck3" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck4" id="deck4" class="label">4.Deck</label>
                <input type="text" name="deck4" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck5" id="deck5" class="label">5.Deck</label>
                <input type="text" name="deck5" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck6" id="deck6" class="label">6.Deck</label>
                <input type="text" name="deck6" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck7" id="deck7" class="label">7.Deck</label>
                <input type="text" name="deck7" class="create_l-input">
            </div>
            <div class="create_l-form">
                <label for="deck8" id="deck8" class="label">8.Deck</label>
                <input type="text" name="deck8" class="create_l-input">
            </div>
            
            <button type="submit" class="btn btn-primary">Create League</button>
        </form>
    </div>
</body>
<footer>
</footer>
</html>

app/templates/create_m.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Create Match</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="create_m-header">
        <h1 class="create_m-h1">CREATE MATCH</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div class="create_m">
        <form method="POST" action="{{ url_for('main.create_m', tournament_id=tournament.id) }}">
            {{ form.hidden_tag() }}
            
            <div class="create_m-form">
                {% for player in tournament_players %}
                <div class="match-container">
                    <label class="create_m-label">Player</label>
                    <br>
                    <br>
                    <div>
                        <label class="match-data">{{ player.player_name }}</label>
                        <br>
                        <br>
                        <label class="create_m-label">Select Deck</label>
                        <br>
                        <br>
                        <select class="selectdecks" name="selectdecks">
                            {% for deck in tournament_decks %}
                                <option value="{{ deck.id }}">{{ deck.deck_name }}</option>
                            {% endfor %}
                        </select>
                        <br>
                        <br>
                        <input type="hidden" name="players" value="{{player.id}}">
                        <div class="checkbox">
                            <input type="checkbox" name="winner" value="{{player.id}}">
                            <label class="datalabel">Winner</label>
                        </div>   
                    </div>
                </div>
                {% endfor %}

            </div>
            <br>
            <button type="submit" class="create_m-button">Create</button>
        </form>
    </div>
</body>
<footer>
</footer>
</html>

app/templates/create_t.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Create Tournament</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="create_t-header">
        <h1 class="create_t-h1">CREATE TOURNAMENT</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div class="create_t">
        <form method="POST" action="{{ url_for('main.create_t', league_id=league.id) }}">
            {{ form.hidden_tag() }}
            
            <div class="create_t-form">
                <label class="create_t-label">Tournament Name</label>
                <input type="text" name="tournament_name" class="create_t-input" required>
            </div>
            <div class="create_t-form">
                <label class="create_t-label">Tournament Players</label>
                {% for player in players %}
                    <div class="checkbox">
                        <input type="checkbox" name="players" value="{{ player.id }}">
                        <label class="datalabel">{{ player.player_name }}</label>
                    </div>
                {% endfor %}
            </div>
            <div class="create_t-form">
                <label class="create_t-label">Tournament Decks</label>
                {% for deck in decks %}
                    <div class="checkbox">
                        <input type="checkbox" name="decks" value="{{ deck.id }}">
                        <label class="datalabel">{{ deck.deck_name }}</label>
                    </div>
                {% endfor %}
            <br>
            <button type="submit" class="create_t-button">Create</button>
        </form>
    </div>
</body>
<footer>
</footer>
</html>

app/templates/current_l.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Active Leagues</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="current_l-header">
        <h1 class="current_l-h1">ACTIVE LEAGUES</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div>
        <ul>
            {% for league in active_leagues %}
            <div class="league-container">
                <div class="league-item">
                    <a>User</a>
                </div>
                <ul>
                    <div class="league-data">
                        <a>{{ league.user.username }}</a>
                    </div>
                </ul>
                <div class="league-item">
                    <a>League Name</a>
                </div>
                <ul>
                    <div class="league-data">
                        <a>{{ league.league_name }}</a>
                    </div>
                </ul>
                <div class="league-item">
                    <a>Players</a>
                </div>
                <ul>
                    {% for participant in league.participants %}
                    <div class="league-data">
                        <a>{{ participant.player_name }}</a>
                    </div>
                    {% endfor %}
                </ul>
                <div class="league-item">
                    <a>Decks</a>
                </div>
                <ul>
                    {% for deck in league.decks %}
                    <div class="league-data">
                        <a>{{ deck.deck_name }}</a>
                    </div>
                    {% endfor %}
                </ul>
                <br>
                <br>
                <a href="{{ url_for('main.create_t', league_id=league.id) }}" class="current_l-button">Create Tournament</a>
                <a href="{{ url_for('main.current_t', league_id=league.id) }}" class="current_l-button">Tournaments</a>
                <br>
                <br>
            </div>
            <br>
            
            {% endfor %}
        </ul>
    </div>
</body>
<footer>
</footer>
</html>

app/templates/current_m.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Tournament Matches</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="current_m-header">
        <h1 class="current_m-h1">TOURNAMENT MATCHES</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div>
        <ul>
            {% for match in matches %}
            <div class="current_m-container">
                <div class="current_m-item">
                    <a>Tournament Name</a>
                </div>
                <ul>
                    <div class="current_m-data">
                        <a>{{ tournament.tournament_name }}</a>
                    </div>
                </ul>
                <table>
                    <thead>
                        <tr>
                            <th>Players</th>
                            <th>Winner</th>
                            <th>Decks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for participant in tournament.participants %}
                        <tr>
                            <td>{{ participant.player_name }}</td>
                            <td>
                                {% if participant in match.winners %}
                                    Winner
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
     
                        {% for deck in match.matchdecks %}
                            <tr>   
                                <td class="match-decks">{{ deck.deck_name }}</td>
                            </tr>  
                            {% if tournament.participants|length == 2 %}
                            <style>
                                td.match-decks{
                                    position: relative;
                                    right: -140px;
                                    top: -66px;
                                }
                            </style>
                            {% endif %}
                            {% if tournament.participants|length == 3 %}
                            <style>
                                td.match-decks{
                                    position: relative;
                                    right: -140px;
                                    top: -99px;
                                }
                            </style>
                            {% endif %}
                            {% if tournament.participants|length == 4 %}
                            <style>
                                td.match-decks{
                                    position: relative;
                                    right: -140px;
                                    top: -132px;
                                }
                            </style>
                            {% endif %}
                        {% endfor %}
                        
                    </tbody>
                </table>
                <a href="{{ url_for('main.delete', match_id=match.id, tournament_id=tournament.id) }}" class="eliminate-button"><img src="{{ url_for('static', filename='img/icons8-trash-26.png') }}" alt="Delete Match" width="20" height="20"></a>
            </div>
            {% endfor %}
        </ul>
    </div>
</body>
<footer>
</footer>
</html>

app/templates/delete.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Delete Match</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="delete-header">
        <h1 class="delete-h1">DELETE MATCH</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <h2 class="delete-h2">Are you sure you want to delete the match?</h2>
    <form method="POST">
        <button class="delete-button" type="submit" name="delete">DELETE MATCH</button>
    </form>
</body>
<footer>
</footer>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='home_style.css') }}">
    <title>Home</title>
    <script>
        function toggleMenu() {
            var menu = document.getElementById('menu-list');
            if (menu.style.display === 'block') {
                menu.style.display = 'none';
            } else {
                menu.style.display = 'block';
            }
        }
    </script>
</head>
<body>
    <div class="home-header">
        <h1>HOME</h1>
        <button id="menu-button" onclick="toggleMenu()">Menu</button>
        <ul id="menu-list">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.eliminate') }}">Eliminate</a></li>
            <li><a href="{{ url_for('main.settings') }}">Settings</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        </ul>
    </div>
    <div class="home">
        <form method="post" action="{{ url_for('main.create_l') }}">
            <button type="submit" name="create_l">Create League</button>
        </form>

        <form method="post" action="{{ url_for('main.current_l') }}">
            <button type="submit" name="current_l">Leagues</button>
        </form>

        <form method="post" action="{{ url_for('main.eliminate') }}">
            <button type="submit" name="eliminate">Eliminate</button>
        </form>
    </div>
</body>
<footer>
</footer>
</html>